server:
  port: 9002
spring:
  redis:
    database: 0
    port: 6379
    host: 127.0.0.1
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: -1
  application:
    name: sso-mock-app2
sso:
  server:
    url: http://127.0.0.1:9003
  client:
    protect: /hello